WQXR: Refinements after second week of use (#4)
* Add example with long composer name

This came up today during my testing of the new vertical scrolling mode

Composers with long names don't get properly wrapped in WrappedText widgets (would be nice if it could break on hyphens as well as spaces)

* Fix issue with soloist data that uses `role`

This was an accidental catch, I noticed this error when I sat down to work on the library this afternoon

The piece that was on was using the "role" part of the soloist data, instead of the "instrument" line (like, it was a soloist but the "instrument" section was blank) so the app was erroring:

```
2023/07/17 16:59:49 error loading applet: error running script: Traceback (most recent call last):
  wqxr/wqxr.star:138:30: in main
  wqxr/wqxr.star:214:97: in build_people
Error: index 0 out of range: empty list
```

I fixed it by checking for "role" if instruments is empty; seems to work fine; also captured the data for this API response in my mock data

* Remove `max_age`

This is causing a situation where the Tidbyt shows its logo animation once a minute (when the app is pinned) because the max_age runs out and the heartbeat from Tidbyt's cloud doesn't seem to contain another image to show

I'm not exactly sure how to fix this but I think just removing it for now will help

* Add example with long song title